name: ChReDp

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/rme/loop.bat" -OutFile "loop.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/ChReDp/ChReDp.bat" -OutFile "ChReDp.bat"
          

      - name: ChReDp
        run: cmd /c ChReDp.bat

      - name: Time Counter
        run: cmd /c loop.bat
