name: CRM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: CLU
        run: |
          Set-LocalUser -Name "baynar" -Password (ConvertTo-SecureString -AsPlainText $Env:WIN_PASS -Force)
        env:
          WIN_PASS: ${{ secrets.WIN_PASS }}
      
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/rme/crm/crmdown.bat" -OutFile "crmdown.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/rme/crm/CRM.bat" -OutFile "CRM.bat"

      - name: CRM
        run: cmd /c CRM.bat

      - name: crmdown
        run: cmd /c crmdown.bat

      - name: Time Counter
        run: sleep 99999

      - name: crmdown
        run: cmd /c crmdown.bat

      - name: Time Counter
        run: sleep 99999
