name: MacOS Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        MAC_REALNAME: ${{ secrets.MAC_REALNAME }}

    - name: Install and Run SSHX on macOS
      run: |
        curl -sSf https://sshx.io/get | sh -s run

    - name: Keep the Job Running
      run: sleep 999999

