name: Connect to macOS via VNC using Ngrok

on:
  push:
    branches:
      - main

jobs:
  connect-to-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        # Install Ngrok
        curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}  # Correctly pass the token as an argument

    - name: Start Ngrok for VNC tunnel
      run: |
        # Start Ngrok to expose VNC port (usually 5900)
        ./ngrok tcp ${{ secrets.VNC_HOST }}:${{ secrets.VNC_PORT }} &

    - name: Wait for Ngrok to start
      run: sleep 10

    - name: Retrieve Ngrok URL
      run: |
        # Fetch the Ngrok URL
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Ngrok URL: $NGROK_URL"
        
    - name: Connect to VNC using Ngrok URL
      run: |
        # Install VNC client and connect (requires 'tigervnc' or similar)
        brew install tigervnc-viewer
        vncviewer $NGROK_URL -passwd ${{ secrets.VNC_PASSWORD }}
