name: Install Chrome Remote Desktop Host on macOS

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  install-and-setup:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"  # Add Homebrew to the path

    - name: Install Chrome Remote Desktop Host
      run: |
        brew install --cask chrome-remote-desktop-host

    - name: Start Chrome Remote Desktop Host
      run: |
        /opt/google/chrome-remote-desktop/start-host --code="<auth_code>" \
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
        --name=$(hostname)  # You can customize the hostname

    - name: Keep Workflow Running (Optional)
      run: |
        sleep 999999  # Keep the workflow running indefinitely for troubleshooting if needed
