name: Setup Chrome Remote Desktop on macOS

on:
  push:
    branches:
      - main

jobs:
  install-and-setup-chrome-remote-desktop:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"  # Add Homebrew to path

    - name: Install Chrome Remote Desktop
      run: |
        brew install --cask chrome-remote-desktop

    - name: Install Google Chrome
      run: |
        brew install --cask google-chrome

    - name: Set up Desktop Environment (Optional, for headless macOS)
      run: |
        sudo /bin/bash -c "echo -e '\n# Set up environment for CRD\nexport CHROME_REMOTE_DESKTOP_EXECUTABLE='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' >> ~/.bash_profile"

    - name: Start Chrome Remote Desktop (with OAuth code)
      run: |
        echo "Starting Chrome Remote Desktop with OAuth code..."
        DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="4/0AeanS0aIlYv9bkVwi9XVWIhlMcvVmOMhIY87_z6FvPxZLK2_nsu0LVPljSzdZROZAjLPVw" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=$(hostname)

    - name: Keep Workflow Running (Optional, for troubleshooting)
      run: |
        sleep 999999  # Keeps the job running indefinitely to allow for debugging if needed
