name: Setup Chrome Remote Desktop on macOS

on:
  push:
    branches:
      - main

jobs:
  install-and-setup-chrome-remote-desktop:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"  # Add Homebrew to path

    - name: Install Chrome Remote Desktop
      run: |
        brew install --cask chrome-remote-desktop

    - name: Install Google Chrome
      run: |
        brew install --cask google-chrome

    - name: Start Chrome Remote Desktop Host
      run: |
        # Authenticate and start the CRD host
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AeanS0aIlYv9bkVwi9XVWIhlMcvVmOMhIY87_z6FvPxZLK2_nsu0LVPljSzdZROZAjLPVw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
      shell: /bin/bash -e {0}

    - name: Keep the Workflow Running (Optional, to ensure the setup is complete)
      run: |
        sleep 999999  # Keeps the job running indefinitely, allowing time for manual setup if required
