name: AnyDesk Installation

on:
  push:
    branches:
      - main

jobs:
  install-anydesk:
    runs-on: macos-latest

    steps:
    - name: Download AnyDesk DMG
      run: |
        curl -o AnyDesk.dmg https://download.anydesk.com/anydesk.dmg

    - name: Mount DMG
      run: |
        hdiutil attach AnyDesk.dmg -nobrowse -mountpoint /Volumes/AnyDesk

    - name: Install AnyDesk
      run: |
        sudo installer -pkg /Volumes/AnyDesk/*.pkg -target /

    - name: Unmount DMG
      run: |
        hdiutil detach /Volumes/AnyDesk

    - name: Verify AnyDesk Installation
      run: |
        /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --version
