name: Install and Configure Chrome Remote Desktop Host on macOS

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  install-and-setup:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"  # Add Homebrew to the path

    - name: Install Chrome Remote Desktop Host
      run: |
        brew install --cask chrome-remote-desktop-host

    - name: Start Chrome Remote Desktop Host Automatically
      run: |
        /opt/google/chrome-remote-desktop/start-host --code="4/0AeanS0aIlYv9bkVwi9XVWIhlMcvVmOMhIY87_z6FvPxZLK2_nsu0LVPljSzdZROZAjLPVw" \
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
        --name=$(hostname)  # Optionally, customize the hostname

    - name: Verify Installation
      run: |
        # Verify the installation
        which chrome-remote-desktop-host
        # Optionally, check if the process is running
        ps aux | grep chrome-remote-desktop
