name: MacOS Virtual Machine
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      run: |
        chmod +x macos-run.sh
        ./macos-run.sh "PassW@rd" "PassW@rd" "1UsQiVX5yamnqtOQlsFbdCQWaPO_6PkGezQvuw75sJu3HgY8Q" "runneradmin"
    - name: Connecting MacOS with Ngrok to VNC Server
      run: |
        curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Keep Running MacOS System and keepAlive
      uses: mxschmitt/action-tmate@v2
