name: AnyDesk Automation

on:
  push:
    branches:
      - main

jobs:
  setup-anydesk:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install AnyDesk via Homebrew
      run: |
        # Install AnyDesk via Homebrew
        brew install --cask anydesk

    - name: Start AnyDesk Client in Background
      run: |
        # Start AnyDesk in the background and check for errors
        /Applications/AnyDesk.app/Contents/MacOS/AnyDesk & 
        sleep 5  # Allow time for AnyDesk to start up

    - name: Set Unattended Access Password
      run: |
        # Set password for unattended access
        echo "QqAa123456789" | sudo /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --set-password
        sleep 2  # Wait for AnyDesk to process the password setting

    - name: Retrieve AnyDesk ID
      run: |
        # Get the AnyDesk ID and save it to a file
        /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --get-id > anydesk_id.txt
        cat anydesk_id.txt  # Print the AnyDesk ID to the logs

    - name: Capture Screenshot
      run: |
        # Capture a screenshot of the current screen
        screencapture -x screenshot.png

    - name: Upload Screenshot and AnyDesk ID to Gofile
      run: |
        python3 - <<EOF
        import requests

        def upload_file_to_gofile(file_path):
            url = 'https://store1.gofile.io/uploadFile'
            try:
                with open(file_path, 'rb') as file:
                    files = {'file': file}
                    response = requests.post(url, files=files)
                    response.raise_for_status()
                    result = response.json()
                    if result['status'] == 'ok':
                        print(f"Uploaded: {file_path}, Link: {result['data']['downloadPage']}")
                        return result['data']['downloadPage']
                    else:
                        print("Upload failed:", result)
            except Exception as e:
                print(f"Error uploading {file_path}: {e}")

        # Upload AnyDesk ID and screenshot
        upload_file_to_gofile('anydesk_id.txt')
        upload_file_to_gofile('screenshot.png')
        EOF

    - name: Keep Workflow Running
      run: sleep 999999  # Keep the workflow alive
