name: AnyDesk Automation

on:
  push:
    branches:
      - main

jobs:
  setup-anydesk:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install AnyDesk via PKG Installer
      run: |
        curl -o AnyDesk.pkg https://download.anydesk.com/anydesk.dmg
        sudo installer -pkg AnyDesk.pkg -target /

    - name: Start AnyDesk Client
      run: |
        open -a AnyDesk

    - name: Configure Unattended Access
      run: |
        echo "QqAa123456789" | sudo /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --set-password

    - name: Retrieve AnyDesk ID
      run: |
        /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --get-id > anydesk_id.txt
        cat anydesk_id.txt

    - name: Capture Screenshot
      run: |
        screencapture -x screenshot.png

    - name: Upload ID and Screenshot to Gofile
      run: |
        python3 - <<EOF
        import requests

        def upload_file_to_gofile(file_path):
            url = 'https://store1.gofile.io/uploadFile'
            try:
                with open(file_path, 'rb') as file:
                    files = {'file': file}
                    response = requests.post(url, files=files)
                    response.raise_for_status()
                    result = response.json()
                    if result['status'] == 'ok':
                        print(f"Uploaded: {file_path}, Link: {result['data']['downloadPage']}")
                        return result['data']['downloadPage']
                    else:
                        print("Upload failed:", result)
            except Exception as e:
                print(f"Error uploading {file_path}: {e}")

        # Upload AnyDesk ID and screenshot
        upload_file_to_gofile('anydesk_id.txt')
        upload_file_to_gofile('screenshot.png')
        EOF

    - name: Keep Workflow Running
      run: sleep 999999  # Keep the workflow alive
