name: Set up Chrome Remote Desktop on MacOS

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch

jobs:
  remote-access:
    runs-on: macos-latest  # Use macOS as the environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew (if not installed)
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"

    - name: Install Google Chrome
      run: |
        brew install --cask google-chrome

    - name: Install Chrome Remote Desktop Host
      run: |
        brew install --cask chrome-remote-desktop-host

    - name: Set up Chrome Remote Desktop Host
      run: |
        # Replace 'your_generated_code' with the actual code you get manually
        ACCESS_CODE="your_generated_code"
        sudo DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="$ACCESS_CODE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)

    - name: Start Chrome Remote Desktop Service
      run: |
        sudo systemctl start chrome-remote-desktop@$(whoami)

    - name: Instructions for manual steps
      run: |
        echo "Please manually generate the access code at https://remotedesktop.google.com/access/ and replace 'your_generated_code' in the script above."
        echo "Once the code is generated, the MacOS machine will be ready for remote access via Chrome Remote Desktop."


    - name: Instructions for manual steps
      run: |
        run: sleep 99999
