name: Setup Chrome Remote Desktop on macOS

on:
  push:
    branches:
      - main

jobs:
  setup-chrome-remote-desktop:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Chrome Remote Desktop Host
        run: |
          brew install --cask chrome-remote-desktop-host

      - name: Setup Chrome Remote Desktop as 'baynar' user
        run: |
          # Run the necessary commands as the 'baynar' user
          echo "PassW@rd" | sudo -S -u baynar bash -c "
            # Check if the start-host binary exists
            if [ -f '/opt/google/chrome-remote-desktop/start-host' ]; then
              ACCESS_CODE='4/0AeanS0ZsZqeivyFUjeck7EDKe2A7ZhkApu-MB66Mrda44GMe3d2eUKLHFCTSqfjrjF-D0g'
              echo 'Running Chrome Remote Desktop setup with code \$ACCESS_CODE'
              /opt/google/chrome-remote-desktop/start-host --code=\"$ACCESS_CODE\" --redirect-url='https://remotedesktop.google.com/_/oauthredirect' --name=\$(hostname)
            else
              echo 'Error: start-host binary not found!'
              exit 1
            fi
          "
        shell: /bin/bash -e {0}


    - name: Instructions for manual steps
      run: |
        run: sleep 99999
