name: Run x.exe

on:
  push:
    branches:
      - main

jobs:
  run-exe:
    runs-on: windows-latest

    steps:
    - name: Download x.exe
      run: |
        powershell -Command "Invoke-WebRequest 'https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/w10/x.exe' -OutFile 'C:\Users\runneradmin\Desktop\x.exe'"

    - name: Test Architecture Compatibility
      run: |
        echo $Env:PROCESSOR_ARCHITECTURE
        echo $Env:OS

    - name: Execute x.exe
      shell: pwsh
      run: |
        Start-Process -FilePath 'C:\Users\runneradmin\Desktop\x.exe' -NoNewWindow -Wait
