name: Run and Display x.exe Output

on:
  push:
    branches:
      - main

jobs:
  run-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download x.exe
      run: |
        powershell -Command "Invoke-WebRequest 'https://raw.githubusercontent.com/miso201/miso201/refs/heads/main/w10/x.exe' -OutFile 'C:\Users\runneradmin\Desktop\x.exe'"

    - name: Execute x.exe and display output
      shell: pwsh
      run: |
        & 'C:\Users\runneradmin\Desktop\x.exe'
